/// Flutter icons MyFlutterApp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData r_shoulder_p = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r_smallleg_p = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r_waist_p = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r_chest_p = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r_arm_p = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l_smallleg_p = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l_shoulder_p = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l_chest_p = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l_waist_p = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l_arm_p = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData abdomen_p = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leg_p = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
